### ISSUE TITLE
Position assertions do not assert zero distance correctly

### ISSUE THREAD

**Issue by weizhongtan** [msmps/cypress-layout-inspector#13]
When passing a value of `0` to the `below` or `above` assertions, the assertions checks that the actual distance is greater than or equal to `0`, rather than exactly equal. I think this is fine as a default if no distance is provided, but when providing a value, I think it makes more sense to do an exact check.

This is because the logic assumes that if the distance is `0` you don't want an exact check:
https://github.com/msmps/cypress-layout-inspector/blob/aaeae34d4ae65a55038222ae86ab3caf933dc33c/src/assertions/position.js#L88

Happy to raise a PR to fix this if you agree that this behaviour is a bug.

Cheers

**Comment by msmps** [comment]
Apologies for the long delay in my response and thank you for flagging this, you raise a valid point and this did not cross my mind previously!

I welcome your contributions, please raise if you do not have the time and I will make sure this is updated.

Thanks

**Comment by weizhongtan** [comment]
No problem! Thanks, I'll see if I can get a PR together over the next few weeks.
