### ISSUE TITLE
Feature request: inside

### ISSUE THREAD

**Issue by david-boydell** [msmps/cypress-layout-inspector#15]
Hi,

One feature that would be incredibly useful is an assertion to check whether one element is inside another element. An example integration test could be:
```
  it('block-2 should be inside block-1', () => {
      cy.get('.block-2').should('be.inside', '.block-1');
  });

  it('block-2 should be inside block-1 by 25px', () => {
      cy.get('.block-4').should(
          'be.inside',
          '.block-1',
          { right: 25, left: 25, top: 25, bottom: 25 }
      );
  }); 
```

The html test page can be found here: https://gist.github.com/david-boydell/89c4fe1c11685341f533c31b29f7d37f

I have tried to come up with a working example but I can't seem to get the assertion to be built, the error is `The chainer inside was not found. Could not build assertion`. I imagine you may have more luck so thought I'd put in a request.

**Comment by msmps** [comment]
Hi @david-boydell,

Thank you for your request, it has actually cropped up a few times not just as an issue but word of mouth!

I've finally had the time to do a first-pass, feel free to check it out and report back any issues you may encounter.

Thanks

**Comment by david-boydell** [comment]
Great, thank you very much!

**Comment by david-boydell** [comment]
That's great @msmps, I'm very grateful thank you.

**Comment by msmps** [comment]
You're welcome, thank you for the contribution!

@all-contributors please add @david-boydell for ideas
