### ISSUE TITLE
Overflow and overlap detection

### ISSUE THREAD

**Issue by satueveliina** [msmps/cypress-layout-inspector#6]
Hi, 

I was just working on something similar for Cypress when I came across this project. Instead of doing double work, perhaps it would make sense for me to to extend this project. The two new assertions I would implement are overflow and overlap detection. Perhaps also centering detection. 

Do these seem like something you see as part of this library?

**Comment by msmps** [comment]
Hi @satueveliina,

Absolutely, that sounds great...

I had some work in the pipeline for center-detection inside of parent elements but please feel free to contribute!

I look forward to your additions

**Comment by satueveliina** [comment]
The PR is out: https://github.com/msmps/cypress-layout-inspector/pull/8

Feel free to criticize and nitpick, I'm all for those in code reviews :-)
