### ISSUE TITLE
dist folder not found

### ISSUE THREAD

**Issue by jpreddygithub** [msmps/cypress-layout-inspector#74]
add-support.js file has

require('./dist/index');

but i don't see any dist folder. it causes test to fail

**Comment by msmps** [comment]
Hi, thanks for your question.

If this is for development/contribution purposes and you cloned this repository directly then you will first need to run

```bash
npm run build
```

If this is for use as a dependency in a project however you should be fine to install as normal

```bash
npm install --save-dev cypress-layout-inspector
```
